# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorder_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=500)),
                ('media_url', models.FileField(blank=True, upload_to='D:\\Git\\pincorder-backend\\pincorder\\media\\raw_upload')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorder_engine.Recording')),
            ],
        ),
        migrations.AlterField(
            model_name='recordingfile',
            name='file_url',
            field=models.FileField(upload_to='D:\\Git\\pincorder-backend\\pincorder\\media\\raw_upload'),
        ),
    ]
