# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorder_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recorder_engine.Course'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='status',
            field=models.CharField(default='UPLOADED', max_length=200),
        ),
    ]
