# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recorder_engine', '0002_auto_20170405_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='authorized_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
