# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recorder_engine', '0003_course_authorized_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingFile',
            fields=[
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recorder_engine.Recording')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('file_url', models.FileField(upload_to='D:\\GitHub\\space-labs-backend\\audio_recorder\\media\\raw_upload')),
            ],
        ),
        migrations.RemoveField(
            model_name='recording',
            name='media_url',
        ),
        migrations.AlterField(
            model_name='recording',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=200),
        ),
    ]
